const subFuturoJ = {
  futuroJ: [
    "<algoQueCaeJ> <verboCaeObjDirecJ> <enLoQueCaeJ>",
    "Sabrás <verboInfJ>",
    "Verás <verboInfVisionJ>",
    "Verás <complementoVisionJ>",
    "Si <verboCondicionalPresenteJ> <sustantivoCondicionalJ>, deberás <verboDeberFuturoJ>"
  ],

  //componenetes futuro:

  //futuro 0 algo que cae

  algoQueCaeJ: [
    "Un viento",
    "Un golpe de suerte",
    "Un presagio",
    "Un nuevo amor",
    "Un amor <adjAmorJ>",
    "Un mensaje",
    "Una buena nueva",
    "Una noticia",
    "Una llovizna",
    "Una brisa",
    "Un anuncio"
  ],
  adjAmorJ: [
    "inesperado",
    "súbito",
    "azul",
    "verde",
    "amarillo",
    "violeta",
    "pasajero",
    "duradero",
    "agridulce"
  ],
  verboCaeObjDirecJ: [
    "tocará",
    "golpeará",
    "rozará",
    "caerá sobre",
    "llegará a",
    "sacudirá",
    "se posará sobre"
  ],
  enLoQueCaeJ: [
    "tus pies",
    "tu vida",
    "tu ventana",
    "tu puerta",
    "tu frente",
    "tu pecho",
    "tu camino",
    "tus huesos",
    "tus manos",
    "tu jardín",
    "tu techo",
    "tus rosas",
    "tu alma",
    "tu piel",
    "tu regazo"
  ],

  //futuro 1 sabiduría futura

  verboInfJ: [
    "<verboInfCosasMalasJ> <cosasFuturoMalasJ>",
    "<verboInfCosasBuenasJ> <cosasFuturoBuenasJ>"
  ],
  verboInfCosasMalasJ: [
    "reconocer",
    "evitar",
    "sortear",
    "olvidar",
    "sobrepasar"
  ],
  verboInfCosasBuenasJ: [
    "aceptar",
    "reconocer",
    "bienvenir",
    "atraer",
    "apreciar",
    "encontrar",
    "agradecer"
  ],
  cosasFuturoMalasJ: [
    "las envidias",
    "a las personas <adjPersonasMaloJ>",
    "el pasado <adjPasadoJ>",
    "lo que te hace daño",
    "las críticas",
    "las adversidades",
    "el peligro",
    "las heridas",
    "los traumas",
    "el mal que <adjMalJ>",
    "el miedo",
    "el miedo al cambio",
    "la pereza",
    "el punto más oscuro de la noche"
  ],
  adjMalJ: [
    "acecha",
    "se esconde",
    "se aproxima",
    "se disfraza",
    "se camufla",
    "gira las esquinas"
  ],
  adjPersonasMaloJ: [
    "envidiosas",
    "que no te convienen",
    "que te retrasan",
    "negativas",
    "tóxicas",
    "enmascaradas",
    "disfrazadas",
    "que te detienen",
    "dobles",
    "que te acechan",
    "pesadas",
    "dañinas",
    "violentas"
  ],
  cosasFuturoBuenasJ: [
    "las adversidades",
    "los retos",
    "el pasado <adjPasadoJ>",
    "a las personas <adjPersonasBuenoJ>",
    "el día tras la noche",
    "las oportunidades",
    "la buena salud",
    "el amor",
    "la alegría cotidiana",
    "la felicidad en los pequeños detalles",
    "las pequeñas cosas",
    "el pan",
    "la luz en la oscuridad",
    "el sol en las penumbras",
    "el tiempo que pasa",
    "el trabajo duro",
    "los buenos presagios",
    "la alegría dentro de la tristeza"
  ],
  adjPasadoJ: ["que se empeña", "persistente", "que regresa", "que retorna"],
  adjPersonasBuenoJ: [
    "buenas",
    "que te hagan bien",
    "indicadas",
    "que te aporten",
    "que crezcan contigo",
    "luminosas",
    "que te complementen"
  ],

  //futuro 2 verbovisión

  verboInfVisionJ: [
    "llegar <complementoLlegarJ> <llegarCuandoJ>",
    "pasar <complementoPasarJ>"
  ],
  complementoLlegarJ: [
    "la mañana",
    "la calma",
    "un logro <adjLogroJ>",
    "un trabajo <adjTrabajoJ>",
    "la madrugada",
    "la luz <adjLuzJ>",
    "un dinero sorpresivo"
  ],
  llegarCuandoJ: [
    "en breve",
    "cuando menos esperes",
    "la próxima luna llena",
    "en cuarto menguante",
    "este año",
    "este mes",
    "esta quincena",
    "hoy"
  ],
  adjTrabajoJ: ["nuevo", "mejor", "novedoso", "más recompensante"],
  adjLogroJ: [
    "inesperado",
    "por el que has trabajado",
    "bien merecido",
    "esperado"
  ],
  adjLuzJ: [
    "al final del túnel",
    "que espanta el frío",
    "que ahuyenta las tinieblas",
    "que empuja la oscuridad",
    "que anuncia el día"
  ],
  complementoPasarJ: [
    "la noche",
    "un amor <adjAmorJ>. ¡atrápalo!",
    "una estrella en el cielo",
    "un gato negro <compleGatoNegroJ>",
    "de largo <compleLargoJ>",
    "un ave desde <lugarAveJ>"
  ],
  lugarAveJ: [
    "tu ventana",
    "tu lugar de trabajo",
    "un lugar que amas",
    "que mires hacia arriba"
  ],
  compleLargoJ: [
    "un amor que no te conviene",
    "un viejo amor",
    "una oportunidad engañosa",
    "un daño que esquivaste"
  ],
  compleGatoNegroJ: ["cuando vistas <colorRopaJ>"],
  colorRopaJ: ["rojo", "azul", "amarillo", "verde", "fucsia", "marrón", "gris"],

  // futuro 3 complementovision

  complementoVisionJ: [
    "<sustantivoProyectoJ> <complementoProyectoJ>",
    "el tiempo <verboReflexTiempoJ> esta semana",
    "<sustantivoObjetoVisionJ>"
  ],
  sustantivoObjetoVisionJ: [
    "la noche <verboReflexNocheJ>",
    "el pan <verboReflexPanJ>",
    "la harina <verboReflexHarinaJ>",
    "el día <verboReflexDiaJ>",
    "tus pies <verboReflexPiesJ>"
  ],
  verboReflexPiesJ: [
    "tropezar",
    "ampollarse",
    "andar sin detenerse",
    "seguir adelante",
    "sumergirse en agua tibia",
    "recibir un masaje"
  ],
  verboReflexDiaJ: [
    "amanecer",
    "oscurecer momentáneamente",
    "correr",
    "mejorar con el paso de las horas",
    "calentarse"
  ],
  verboReflexPanJ: [
    "quemarse un poco",
    "crecer ante tus ojos",
    "echarse a perder",
    "siendo comido",
    "calmando el hambre"
  ],
  verboReflexHarinaJ: [
    "hacerse pan",
    "mojarse",
    "molerse",
    "flotar en el aire",
    "caer al suelo",
    "espesar una sopa"
  ],
  verboReflexNocheJ: ["hacerse día", "pasar", "haciéndose más clara"],
  verboReflexTiempoJ: [
    "detenerse",
    "alargarse",
    "estirarse",
    "volar",
    "pasar más rápido",
    "ralentizarse"
  ],
  sustantivoProyectoJ: [
    "un proyecto",
    "un sueño",
    "un presagio",
    "un anhelo",
    "una plegaria",
    "una esperanza"
  ],
  complementoProyectoJ: ["hacerse realidad", "concretarse", "realizarse"],

  //futuro 4 condicional si + deberás

  verboCondicionalPresenteJ: [
    "quieres",
    "deseas",
    "esperas",
    "anhelas",
    "anticipas",
    "aspiras a",
    "mueres por"
  ],
  sustantivoCondicionalJ: [
    "buena fortuna",
    "un mejor trabajo",
    "encontrar un nuevo amor",
    "alcanzar tus metas",
    "hacer aquella inversión",
    "un cambio de fortuna",
    "cumplir ese sueño",
    "solucionar tus problemas amorosos",
    "mejorar en aquello",
    "tener más generosidad",
    "ayudar a los demás",
    "ayudar a alguien",
    "dar un buen consejo"
  ],

  verboDeberFuturoJ: [
    "volver la mirada hacia tu interior",
    "ver más allá de tu nariz",
    "esforzarte más",
    "primero barrer los pisos de tu propia casa",
    "dar el primer paso",
    "alimentar tanto el cuerpo como el alma",
    "levantar la cabeza y abrir bien los ojos",
    "andar nuevos caminos",
    "escuchar a los que te rodean",
    "dejar ir aquello que te pesa",
    "podar los arbustos de tu jardín",
    "recoger las hojas secas",
    "correr ese kilómetro adicional",
    "levantarte una hora más temprano",
    "pensar antes de actuar",
    "dar un salto de fe",
    "alejarte de las malas influencias",
    "esperar a que hierva el agua",
    "ser más como un río",
    "aprender a ser paciente"
  ]
};

const subMisticoJ = {
  misticoJ: [
    "<sustantivoMistico1J> <verboEmpezarJ> <sustantivoMistico2J>",
    "Cuando <verboCuandoJ>, <consecCuandoJ>",
    "<oracionVirtudJ>",
    "<competenciaInteriorJ>",
    "Hoy te sientes como <sentimientoHoyJ>",
    "Te sentirás como <sentimientoHoyJ>",
    "<virtudJ> es <complementoVirtudJ>"
  ],

  //complementos mistico

  //mistico 0 lo que empieza por

  sustantivoMistico1J: [
    "<sustantivoMistico1MascJ>",
    "<sustantivoMistico1FemJ>"
  ],
  sustantivoMistico1MascJ: [
    "Los mejores momentos",
    "Los mayores logros",
    "Los árboles más viejos",
    "Los grandes logros",
    "Los grandes acontecimientos",
    "Los movimientos telúricos",
    "Los cambios planetarios",
    "Los movimientos estelares",
    "Los amores que se recuerdan",
    "Los mayores sucesos",
    "los grandes cambios"
  ],
  sustantivoMistico1FemJ: [
    "Las mejores cosas de la vida",
    "Las mejores ideas",
    "Las buenas acciones",
    "Las grandes obras",
    "Las mayores vibraciones",
    "Las revoluciones",
    "Las obras más importantes",
    "Las cosas memorables",
    "Las relaciones importantes",
    "Las mentes que revolucionan algo"
  ],
  sustantivoMistico2J: [
    "una humilde semilla",
    "una idea",
    "el aleteo de un insecto",
    "un pequeño temblor",
    "una sola gota de agua",
    "un grano de arena",
    "un primer paso",
    "una acción individual",
    "un acto repetible",
    "un átomo",
    "una chispa inicial",
    "una acción que se encadena a otras",
    "la partícula más pequeña",
    "un solo momento"
  ],
  verboEmpezarJ: [
    "comienzan por",
    "empiezan por",
    "se inician en",
    "se originan en"
  ],

  //mistico 1 cuando + sustantivo = consecuencia

  verboCuandoJ: [
    "abres las ventanas",
    "abres los ojos",
    "abres la puerta",
    "menos lo esperas",
    "las manos se buscan",
    "los brazos se encuentran",
    "dos miradas se conectan",
    "las intenciones se alinean",
    "piensas que se acaba",
    "miras a tu alrededor",
    "te detienes un momento",
    "cuidas tu jardín",
    "paras y respiras",
    "abres las cortinas",
    "miras más allá de ti",
    "vuelves la mirada a tu interior",
    "escuchas a tu corazón",
    "menos lo esperas",
    "sabes esperar"
  ],
  consecCuandoJ: [
    "llueve a cántaros",
    "se llena la vasija",
    "entra el vendaval",
    "sopla el viento",
    "algo nuevo ocurre",
    "se suelta la tormenta",
    "se disipan las nubes",
    "se abre el horizonte",
    "una nueva chispa",
    "se enciende una luz en la noche",
    "amanece el día",
    "baja la marea",
    "sube la marea",
    "brillan más los astros",
    "sopla el viento en una nueva dirección",
    "se prende la lumbre",
    "calienta la fogata",
    "el río sigue su curso",
    "se descongela el hielo",
    "el jardín florece",
    "se encience la llama"
  ],

  //mistico 2 Oración Virtud

  oracionVirtudJ: [
    "<virtudJ> triunfa sobre <contraVirtudJ>",
    "<virtudJ> vencerá",
    "<virtudJ> es más fuerte",
    "<virtudJ> prevalece al final del día",
    "<virtudJ> está dentro de ti",
    "<virtudJ> está en tus manos",
    "<virtudJ> asoma en la mañana",
    "<virtudJ> se mantiene, con empeño"
  ],
  virtudJ: [
    "La honestidad",
    "La paciencia",
    "La empatía",
    "El amor sincero",
    "La perseverancia",
    "La valentía",
    "La decencia",
    "La gratitud",
    "El sacrificio",
    "La amabilidad",
    "El compromiso",
    "La lealtad",
    "La serenidad",
    "El amor",
    "La sinceridad",
    "La constancia",
    "La vida"
  ],
  contraVirtudJ: [
    "la pereza",
    "la rutina",
    "los obstáculos",
    "la injusticia",
    "el hastío",
    "la desesperanza",
    "la ingratitud",
    "la monotonía",
    "la antipatía",
    "la envidia",
    "el olvido"
  ],

  //mistico 3 Una batalla en tu interior

  competenciaInteriorJ: [
    "<virtudJ> y <contraVirtudJ> libran una batalla en tu interior",
    "<virtudJ> y <contraVirtudJ> luchan dentro de ti",
    "<virtudJ> y <contraVirtudJ> se enfrentan en tu pecho",
    "<virtudJ> y <contraVirtudJ> luchan en tu corazón"
  ],

  //mistico 4 Hoy te sientes como

  sentimientoHoyJ: [
    "un velero en altamar",
    "un barco de papel que lleva horas en el agua",
    "la arena que besa el mar",
    "un pan puesto al sol",
    "un pan que en la puerta del horno se quema",
    "una estrella fugaz",
    "Sirio, la estrella más brillante del cielo",
    "las flores en primavera",
    "el agua de un arroyo cristalino",
    "un roble",
    "un beso que se lanza al aire",
    "un mensaje en una botella",
    "un león en una jaula",
    "una leona que defiende a sus crías",
    "una vaca que mira el mar",
    "un perrito melancólico",
    "una sandía en el verano",
    "un oasis en el desierto",
    "el rocío de la madrugada",
    "un venado que bajo el sol descansa",
    "las primeras hojas de la primavera",
    "los colores del otoño",
    "el sol en medio del invierno",
    "un vaso medio lleno",
    "la pulpa carnosa de las cerezas",
    "un susurro dicho al oído",
    "el viento entre los árboles",
    "un huracán",
    "la tormenta que se calma",
    "la calma que anticipa la tormenta",
    "el mango en su mejor momento",
    "un postre que endulza un almuerzo",
    "la nieve",
    "el mar en calma",
    "la madrugada",
    "una aguja en un pajar",
    "el café de la mañana",
    "mantequilla sobre pan",
    "una hoja que lleva el viento",
    "una manzana sumergida en caramelo",
    "el metal en expansión",
    "la música de las esferas",
    "un planeta girando",
    "un sol que ilumina sus planetas",
    "un polluelo emparamado",
    "el barco que se sobrepone a la tormenta",
    "pera en dulce",
    "duraznos en almíbar",
    "pan recién horneado",
    "un pastel de cumpleaños",
    "un girasol",
    "brisa de agosto",
    "atardecer de novimebre",
    "el mar caribe",
    "el mar del norte",
    "plomo",
    "el acero más fuerte",
    "madrugada de junio",
    "un osezno que emerge en primavera",
    "la calma del invierno",
    "una lechuga",
    "vino dulce",
    "champán efervescente"
  ],

  // Místico 5: Algo es la respuesta

  complementoVirtudJ: [
    "más fuerte",
    "la respuesta",
    "la salida",
    "ungüento sobre la herida",
    "la llave que abre la puerta",
    "debilidad y fortaleza",
    "talismán colgado al cuello",
    "el café de la mañana",
    "tu pan de cada día",
    "la cumbre de tu montaña"
  ]
};

const subFuturoS = {
  futuroS: [
    "se avecinan sorpresas",
    "deberás tomar decisiones apresuradas",
    "recuperarás la confianza",
    "vendrá una alegría que no esperas",
    "vendrá un día de suerte",
    "vendrán días rutinarios",
    "se acercan retos complicados",
    "Cuidado. Podrían alejarse de tí",
    "Atención. Podrías enamorarte",
    "Ojo. Sé gentil con los que te rodean",
    "tus planes previstos se trastornarán",
    "viene un mes de mucho movimiento emocional",
    "vendrán momentos en los que deberás tomar riesgos",
    "vendrá un accidente si no tienes cuidado",
    "tendrás que huir de los compromisos",
    "días relajados por venir",
    "buenas noticias te alegrarán"
  ]
};

const subRitoS = {
  ritosS: [
    "<cantidadS#CAPITALIZE#> <objetoMagicoS>",
    "<objetoMagicoS#CAPITALIZE#>",
    "baño de <sustanciaS> <momentoDelDiaS>",
    "baño de <sustanciaS> <cuandoTeJ>",
    "un té de <tipoTeJ> <cuandoTeJ>"
  ],
  //Complementos ritosJ

  //ritos 3 Un té a cierta hora

  tipoTeJ: [
    "ruda",
    "caléndula",
    "manzanilla",
    "menta",
    "yerbabuena",
    "canela",
    "valeriana",
    "diente de león",
    "albahaca",
    "jazmín",
    "hinojo",
    "salvia",
    "tomillo",
    "toronjil",
    "citronela",
    "melisa",
    "perejil",
    "limonaria",
    "gengibre",
    "limón y miel",
    "limón",
    "genjibre y miel",
    "frutos rojos",
    "hoja de coca",
    "cáscara de naranja",
    "lavanda",
    "anís",
    "flor de jamaica",
    "cardamomo"
  ],
  cuandoTeJ: [
    "en ayunas",
    "antes de dormir",
    "después de almorzar",
    "con la cena",
    "a las 5 de la tarde",
    "al atardecer",
    "cuando la noche se haga día",
    "cuando te falten fuerzas",
    "cuando el amor te inunde",
    "cuando falte la paciencia",
    "cuando venga la pasión",
    "con la merienda",
    "cuando necesites esperanza",
    "cuando sientas frío",
    "cuando oscurezca",
    "antes de trabajar",
    "en lugar de postre"
  ],
  cantidadS: [`${Math.floor(2 + Math.random() * 8)}`, "muchas"],
  objetoMagicoS: ["velas <colorS>", "piedras de <gemaS>"],
  colorS: [
    "blancas",
    "verdes",
    "rojas",
    "azules",
    "púrpuras",
    "violeta",
    "amarillas"
  ],
  gemaS: [
    "amatista",
    "topacio",
    "lapislázuli",
    "ópalo",
    "ámbar",
    "turquesa",
    "jade",
    "cuarzo",
    "zircón"
  ],
  // rito acción
  sustanciaS: [
    "agua bendita",
    "champaña",
    "agua de flores",
    "perfume fino",
    "agua de ajo",
    "té de ajenjo",
    "leche",
    "agua azucarada",
    "gelatina sin sabor",
    "vino blanco",
    "vino tinto",
    "sangre de drago",
    "agua de valeriana",
    "aceite de árbol de té",
    "aceite de coco",
    "aceite de linaza",
    "aceite de almendra",
    "bálsamo de lavanda",
    "aceite de olivas",
    "aceite de baobab",
    "clavos y canela",
    "rayos de sol",
    "lluvia",
    "agua de mar",
    "abrazos",
    "besos",
    "sombra",
    "cumplidos",
    "halagos"
  ],
  momentoDelDiaS: [
    "en la madrugada",
    "al anochecer",
    "en luna llena",
    "en luna nueva",
    "en cuarto menguante"
  ]
};

const subJustificaS = {
  // justifica
  justificaS: [
    "<circunstanciaS#CAPITALIZE#> <valoracionS> para la casa de <cuerpoSignoS>",
    "Con <faseLunarS> se <acercamientoS> un <circunstanciaS> <valoracionS>",
    "<constelacionJ#CAPITALIZE#> en el firmamento <acercamientoS> un <circunstanciaS> <valoracionS>"
  ],
  acercamientoS: [
    "atrae",
    "visumbra",
    "predice",
    "pronostica",
    "presagia",
    "augura",
    "anuncia",
    "manifiesta"
  ],
  circunstanciaS: [
    "momento",
    "presagio",
    "futuro",
    "acontecimiento",
    "lugar",
    "tiempo",
    "encuentro"
  ],
  valoracionS: [
    "bueno",
    "espléndido",
    "magnífico",
    "excelente",
    "sin igual",
    "maravilloso",
    "espectacular",
    "hermoso",
    "bello",
    "auguroso",
    "perfecto",
    "malo",
    "terrible",
    "tenaz",
    "complejo",
    "duro",
    "venturoso",
    "gris",
    "aciago",
    "blanco",
    "claro",
    "iluminador",
    "diáfano",
    "revelador",
    "misterioso",
    "místico",
    "turbulento",
    "peludo",
    "neblinoso",
    "oscuro",
    "retador",
    "aguado",
    "denso",
    "seco",
    "salado",
    "fulgurante",
    "resplandeciente",
    "determinante",
    "gozoso",
    "doloroso",
    "penoso",
    "incómodo",
    "reflexivo",
    "pantanoso",
    "climático",
    "simpático"
  ],
  cuerpoSignoS: ["<cuerpoCelesteS#CAPITALIZE#>", "<signoS>"],
  cuerpoCelesteS: [
    "luna",
    "sol",
    "marte",
    "venus",
    "mercurio",
    "venus",
    "plutón",
    "júpiter",
    "saturno",
    "urano",
    "neptuno"
  ],
  faseLunarS: [
    "luna nueva",
    "luna creciente",
    "cuarto creciente",
    "luna gibosa creciente",
    "luna llena",
    "luna gibosa menguante",
    "cuarto menguante",
    "luna menguante",
    "luna negra",
    "alineaciones estelares",
    "el lucero del alba",
    "la estrella de la tarde",
    "alineación de los astros",
    "tormentas solares",
    "<cuerpoCelesteS> en retroceso",
    "ascendente en <signoS>",
    "estrella vespertina",
    "estrella matutina",
    "agrupamiento sideral",
    "conjunción astral",
    "coordinación planetaria",
    "desencuentros estelares"
  ],
  constelacionJ: [
    "andrómeda",
    "canis major",
    "canis minor",
    "argo navis",
    "casiopea",
    "centaurus",
    "crux",
    "corona australis",
    "corona borealis",
    "delphinus",
    "draco",
    "hércules",
    "hydra",
    "pegaso",
    "perseo",
    "constelación siete cabritas",
    "sirius",
    "musa paradisiaca",
    "ananas comosus",
    "persea americana",
    "solanum melongena",
    "prunus persica",
    "malus domestica",
    "ursus maritimus",
    "castor",
    "polux"
  ]
};

const subSerS = {
  serS: [
    "Como buene <signoS>, eres <vicioOVirtudS>",
    "Tu mayor virtud es ser <virtudS>",
    "Tu mayor defecto es ser <vicioS>",
    "No dejes que las <circunS> opaquen tu <valorS>",
    "Eres <valorS>, <valorS>, <valorS>",
    "Tienes <valorS> para vivir una vida <virtudFemS>",
    "Eres <valorSerJ> <circunstanciaSerJ>"
  ],
  circunS: ["vicisitudes", "circunstancias", "malas energías"],
  valorS: [
    "empatía",
    "amor",
    "fortaleza",
    "lugar",
    "energía",
    "aura",
    "conocimiento",
    "sabiduría",
    "color",
    "llamado espiritual",
    "alma",
    "panorama astral",
    "estrella",
    "llamamiento",
    "llama",
    "fuego",
    "agua",
    "aire",
    "tierra",
    "huracán",
    "revelación",
    "sueño",
    "nube",
    "astro",
    "luz",
    "calor",
    "dudas",
    "preguntas",
    "inquietud",
    "movimiento",
    "pan",
    "alimento",
    "sed",
    "firmeza",
    "deseo",
    "espera",
    "espejo",
    "camino",
    "intriga",
    "controversia",
    "espuma",
    "resiliencia",
    "consistencia",
    "bosque",
    "brisa",
    "árbol",
    "brote",
    "sol",
    "ensoñación"
  ],
  vicioOVirtudS: ["<vicioS>", "<virtudS>"],
  vicioS: [
    "impaciente",
    "poco sociable",
    "gris",
    "pelude",
    "brumose",
    "grumose",
    "fantasma",
    "electricidad",
    "mucho voltaje",
    "puerta cerrada",
    "laberinto"
  ],
  virtudS: [
    "alegre",
    "imponente",
    "inteligente",
    "perseverante",
    "amigable",
    "sociable",
    "buena gente",
    "paciente",
    "fogose",
    "sensual",
    "púrpura",
    "cerúleo",
    "carmín",
    "escarlata",
    "turquesa",
    "transparente",
    "agua fresca",
    "dulce",
    "sol radiante",
    "sinceridad",
    "gatune",
    "leone",
    "esponjose"
  ],
  virtudFemS: [
    "alegre",
    "imponente",
    "inteligente",
    "perseverante",
    "amigable",
    "sociable",
    "buena gente",
    "paciente",
    "fogosa",
    "sensual",
    "púrpura",
    "cerúlea",
    "carmín",
    "escarlata",
    "turquesa",
    "transparente",
    "fresca",
    "dulce",
    "radiante",
    "sincera",
    "gatuna",
    "leona",
    "perruna",
    "osezna",
    "esponjosa",
    "virtuosa",
    "maderosa",
    "temperada",
    "frutosa",
    "estética"
  ],
  valorSerJ: [
    "una roca",
    "sal",
    "la tormenta",
    "el sol",
    "oxígeno",
    "luz",
    "el fresco",
    "la calma",
    "la calidez",
    "lluvia",
    "brillo",
    "paz",
    "<colorSerJ>",
    "una melodía",
    "un salto"
  ],
  colorSerJ: ["azul", "verde", "transparencia", "verdor", "turquesa"],
  circunstanciaSerJ: [
    "en el río",
    "en el agua",
    "en el mar",
    "en la arena",
    "en la mañana",
    "en la tarde",
    "en la madrugada",
    "en la adversidad",
    "en la pradera",
    "en el horizonte",
    "tras las montañas",
    "en el aire",
    "en la vida de los demás"
  ]
};

const gramaticaConjunta = {
  base: ["<opcionA>", "<opcionB>", "<opcionC>"],
  opcionA: ["<serS>.\n<futuros>.\n<misticoJ>."],
  opcionB: ["<futuros>.\n<justificaS>.\n<ritosS#CAPITALIZE#>."],
  opcionC: ["<justificaS>.\n<serS>.\n<futuros>."],
  futuros: ["<futuroJ>", "<futuroS#CAPITALIZE#>"],
  ...subFuturoJ,
  ...subMisticoJ,
  ...subFuturoS,
  ...subRitoS,
  ...subJustificaS,
  ...subSerS
};

module.exports = gramaticaConjunta;
